---

- name: Master
  hosts: master
  vars:
    spark_master: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
  roles:
    - spark

- name: Workers
  hosts: workers
  vars:
    spark_master: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
  roles:
    - spark
