---

- name: Master
  hosts: master
  vars:
    zookeeper_host: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
    accumulo_master: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
  roles:
    - accumulo

- name: Workers
  hosts: workers
  vars:
    zookeeper_host: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
    accumulo_master: "{{ hostvars['master']['ansible_' + eth]['ipv4']['address'] }}"
  roles:
    - accumulo
