---
#Note: this will only terminate a running cluster
# it will have no effect on stopped cluster
- name: Terminating Cluster
  hosts: localhost
  gather_facts: False
  
  tasks:
    - include_vars: group_vars/cluster.yml  

    - name: Terminate Cluster
      local_action: 
        module: ec2 
        region: "{{ region }}" 
        instance_ids: "{{ cluster_instance_ids }}"
        state: 'absent'

    - name: Delete the cluster VPC
      local_action:
        module: ec2_group
        region: "{{ region }}"
        name: "{{ cluster_name }}"
        description: "{{ cluster_name }} security group"
        state: absent