---

#This is needed for Dev, Production should use nightly build AMIs
- name: Update APT cache
  apt: update_cache=yes
  when: '"development" in group_names'
  sudo: yes
  
- name: Install OpenJDK 7 JDK
  apt: pkg=openjdk-7-jdk state=present install_recommends=yes
  sudo: yes

- name: There's no place like $JAVA_HOME
  lineinfile:
    dest="/etc/environment"
    regexp="^JAVA_HOME="
    line="JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/jre"
  sudo: yes

- name: Install Git
  apt: pkg=git state=present install_recommends=yes
  sudo: yes

#This allows to rsync and ssh between any host in the clusters
- name: Upload cluster private key to use as id_rsa
  copy:
    src: "{{ ec2_key_file }}"
    dest: ~/.ssh/id_rsa
    mode: 0600
  when: '"development" not in group_names'

- name: Disable SSH known host checking for 172.* subnet
  copy:
    src: ssh_config
    dest: ~/.ssh/config
    mode: 0644
  when: '"development" not in group_names'

- name: Add Cloudera APT key
  apt_key: url=http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh/archive.key state=present
  sudo: yes

- name: Add Cloudera APT repository
  apt_repository:
    repo: "deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/{{ ansible_distribution_release }}/amd64/cdh {{cdh.repo}} contrib"
    state: present
  sudo: yes

- name: Remove 127.0.1.1 from /etc/hosts
  lineinfile:
    dest="/etc/hosts"
    regexp="^127.0.1.1"
    line=""
  sudo: yes
  when: '"development" in group_names'

- lineinfile:
    dest="/etc/security/limits.conf"
    regexp="soft nofile"
    line="* soft nofile 65536"
  sudo: yes

- lineinfile:
    dest="/etc/security/limits.conf"
    regexp="hard nofile"
    line="* hard nofile 65536"
  sudo: yes
