---

#Main tasks for hadoop datanode
- apt: name=hadoop-hdfs-datanode state=present
  sudo: yes

- name: Attach some EBS volumes
  local_action:
    module: ec2_vol
    region: "{{ region }}"
    instance: "{{ instance_id }}"        
    device_name: "{{ item.device }}"
    volume_size: "{{ item.size }}"
  with_items: hdfs.volumes
  when: '"development" not in group_names'

- name: Format EBS Hadoop data partitions as ext3
  filesystem: fstype="ext3" dev="{{ item.device }}"
  with_items: hdfs.volumes
  sudo: yes
  when: '"development" not in group_names'

  # Needed until is in a release:
  #   https://github.com/ansible/ansible/pull/8002
  #
- name: Check if device already has a file system
  command: blkid -c /dev/null -o value -s TYPE {{ item.device }}
  with_items: hdfs.volumes
  register: existing_fs
  changed_when: existing_fs.rc == 2
  failed_when: False
  sudo: yes
  when: '"development" in group_names'

- name: Format Vagrant Hadoop data partitions as ext3
  command: "mkfs.ext3 {{ item.device }} -F"
  with_items: hdfs.volumes
  sudo: yes
  when: '"development" in group_names and existing_fs|changed'

- name: Mount Hadoop data partitions
  mount: name="{{item.mount}}" src="{{item.device}}" fstype=ext3 state=mounted
  with_items: hdfs.volumes
  sudo: yes

- file: path="{{item.mount}}" owner=hdfs group=hadoop mode=0755 state=directory
  sudo: yes
  with_items: hdfs.volumes

- service: name=hadoop-hdfs-datanode state=started enabled=yes
  sudo: yes
